[package]
name = "rumor-server"
version = "0.1.0"
edition = "2021"

description = "reserved; server for rumor file synchronization protocol"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
